spring:
  profiles:
    active: production

springdoc:
  swagger-ui:
    enabled: true
    path: /docs

persistence:
  url: jdbc:postgresql://task-db:5432/task
  schema: task
  username: task_appl
  password: qwe123
  maxPoolSize: 10